server:
  port: 9100
spring:
  datasource:
    name: shopping_cart
    url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
#连接池
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      min-idle: 10
      max-active: 20
      initial-size: 10
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true